### ISSUE TITLE
Show track names

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#129]
This is important for, say, knowing which pileup is Normal and which is Tumor.

IGV uses a left gutter ("Sequence", "RefSeq Genes"):
![screen shot 2015-05-08 at 10 22 48 am](https://cloud.githubusercontent.com/assets/98301/7538176/37c99fe4-f56c-11e4-81a7-01aab0a5b126.png)

Dalliance shows them as overlaid semi-transparent bubbles ("DNase I"):
![screen shot 2015-05-08 at 10 20 48 am](https://cloud.githubusercontent.com/assets/98301/7538177/37c9e13e-f56c-11e4-8b6b-250af7902603.png)

@jaclynperrone I'd love your thoughts on this! :)

**Comment by jaclynperrone** [comment]
IGV's left gutter is much cleaner than Dalliance's bubbles. The arrow is
explicit, and the text isn't obscuring the data. With Dalliance, I'm not
sure how I would even get those bubbles back if I were to close them
(yikes!). Let's have a chat next week about design for pileup. Would love
to help you out on that front :)

On Fri, May 8, 2015 at 10:24 AM, Dan Vanderkam <notifications@github.com>
wrote:

> This is important for, say, knowing which pileup is Normal and which is
> Tumor.
>
> IGV uses a left gutter ("Sequence", "RefSeq Genes"):
> [image: screen shot 2015-05-08 at 10 22 48 am]
> <https://cloud.githubusercontent.com/assets/98301/7538176/37c99fe4-f56c-11e4-81a7-01aab0a5b126.png>
>
> Dalliance shows them as overlaid semi-transparent bubbles ("DNase I"):
> [image: screen shot 2015-05-08 at 10 20 48 am]
> <https://cloud.githubusercontent.com/assets/98301/7538177/37c9e13e-f56c-11e4-8b6b-250af7902603.png>
>
> @jaclynperrone <https://github.com/jaclynperrone> I'd love your thoughts
> on this! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hammerlab/pileup.js/issues/129>.
>



-- 
Jaclyn Perrone
jaclynperrone.com
