### ISSUE TITLE
Tie mismatch opacity to quality

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#155]
IGV colors mismatched base pairs with high read qualities brightly (green mismatch), whereas lower-quality reads are colored faintly (brown & blue at the bottom):

![screen shot 2015-05-20 at 2 20 30 pm](https://cloud.githubusercontent.com/assets/98301/7733157/6514d2f0-fefb-11e4-91e6-d7fb18c0c113.png)

This is a helpful cue for which ones you should focus on.

**Comment by arahuja** [comment]
+1 if this is an easy add, would be huge

**Comment by danvk** [comment]
IGV maps base quality to opacity in [`getShadedColor`][1].



It has some settings for the scale. Here are the defaults:
![screen shot 2015-07-08 at 3 01 28 pm](https://cloud.githubusercontent.com/assets/98301/8579402/607de5bc-2582-11e5-8073-865ee1d340ce.png)

[1]: https://github.com/igvteam/igv/blob/5e6d242d4a9d9ea8f1f5bb80250ede9aa49a444f/src/org/broad/igv/sam/AlignmentRenderer.java#L948
