### ISSUE TITLE
playground.html does not work without h19.2bit and ensGene.bb

### ISSUE THREAD

**Issue by armish** [hammerlab/pileup.js#163]
[README.md](https://github.com/hammerlab/pileup.js/blob/master/README.md) does not mention about the requirement about a 2bit and a bb file to be able to run the demo from [playground.html](https://github.com/hammerlab/pileup.js/blob/master/playground.html).

![screen shot 2015-06-04 at 5 18 50 pm](https://cloud.githubusercontent.com/assets/7809/7994766/01851a8a-0ade-11e5-87fe-d94e390358c4.png)

How about providing dummy test files to replace those so that people don't need to download them separately for a quick demo?

**Comment by danvk** [comment]
Drat! The easiest way to work around this would be to change the URL in `playground.html` to `http://www.biodalliance.org/datasets/hg19.2bit`. I can change it back for local, offline development if necessary.

**Comment by armish** [comment]
Yeah, that might work -- but do you think the browsers can handle downloading that huge file? 

Back when I was fiddling around with the genome tools, I remember creating custom 2bit genome files from fasta-formatted sequences. Maybe we can generate one for testing and easy-dist purposes. I can look into this if you would like.

**Comment by danvk** [comment]
It doesn't have to download the whole thing. It does range requests for just the relevant bits. Check out `RemoteFile.js` for details.

Slicing the 2bit file would also work, but I don't believe you can start the slice anywhere but the beginning of a contig. I'd be happy to be wrong, though!

**Comment by armish** [comment]
Ah, that design choice does make sense. OK, I think it makes sense to use the original hg19.2bit instead of trying to hack a smaller 2bit file together.
