### ISSUE TITLE
Publish pileup.js as a BioJS component

### ISSUE THREAD

**Issue by armish** [hammerlab/pileup.js#166]
[BioJS](http://biojs.net/) has been gaining quite a lot of attraction from the Bioinformatics community lately and a majority of the early adaptors gained a considerable user base due to this increased visibility.  I think it makes sense to start supporting the framework as it is really not too much of a work. 

This is loosely related to issues #136 and #113; and once done, we can think about adding a short write-up to this F1000 collection to make it even more public: http://f1000research.com/articles/3-56/v1

**Comment by danvk** [comment]
What would this involve, exactly? Is there an api we'd need to implement?

**Comment by armish** [comment]
I once created a BioJS component from scratch, but have never tried adding support to an existing one. I have to dig more into their tutorials to find a few examples, but it should be just a matter of adding a few more dependencies and prepping demos based on their templates.

For the records, official documentation is hosted here: http://edu.biojs.net/
