### ISSUE TITLE
The column containing your selected variant should be highlighted

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/pileup.js#180]
Highlighting the focused column will help orient the user. This behavior can be seen in IGV.

**Comment by danvk** [comment]
i.e. the dotted vertical lines:

![screen shot 2015-06-11 at 6 53 49 pm](https://cloud.githubusercontent.com/assets/98301/8120263/3d17709c-106b-11e5-9c42-7f681239181c.png)
