### ISSUE TITLE
Should reads containing variants be sorted to the top?

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/pileup.js#181]
An open question. It looks like IGV is doing it, which makes the pileup view a little more coherent. Thoughts?

**Comment by danvk** [comment]
Here's what the [IGV manual has to say][1]:

> Users can also specifiy color and also sort reads by various options, including start location, strand, nucleotide, mapping quality, sample tag, or read group tag. For a description of all user-specified color and sort options, see the alignment track pop-up menu.
> 
> For example, to sort alignments:
>
> Right-click a track for the pop-up menu.
> Select a Sort option from the pop-up menu. IGV sorts the alignments that intersect the center line of the display.
> Sorting rearranges rows so that alignments that intersect the center of the display appear in the order specified.  This can cause the alignment layout away from the center line to appear sparse.   To restore the layout to an optimally packed configuration, select Re-pack alignments from the pop-up menu.
>
> Repeat the most recent sort with hotkey ctrl-s.

My interpretation is that the default behavior is to first pile up the reads which intersect the center line, then pile up the others.

[1]: http://www.broadinstitute.org/igv/AlignmentData#thmr_2
