### ISSUE TITLE
Only publish tranformed Javascript code to NPM

### ISSUE THREAD

**Issue by armish** [hammerlab/pileup.js#188]
This enhancement option came up in the context of issues #187 and #175. Specifically, the problem is that publishing non-transformed code causes problems for people building on top of our library and its automated `browserification` (and integration) is extremely problematic.

We currently transform and browserify the code via `grunt prod` and publish the bundled version for people to use on their websites. #175 was an attempt to make the project compatible with the *de facto* browserify tool, but it required us to introduce new dependencies into the project, which was not ideal.

Here is a relevant question (and a workaround to these issues) on StackOverflow: [Can I write npm package in coffeescript?](http://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript). It would be great to refactor pileup to also use this workflow, where we pre-transform the code and only publish the Javascript code to NPM for better compatibility for other people.

**Comment by danvk** [comment]
Summarizing a discussion @armish and I just had:

- We'll move the existing `src` and `test` directories under a top level `src` directory (`src/src`? Maybe just move the `test` directory under `src`).
- We'll transform the code file-by-file into the `build` directory, which will only contain plain JavaScript.

Things we need to work after this change:

- [ ] Running `grunt flow` returns no errors (currently [returns 3][1])
- [ ] Running `grunt test` passes (i.e. running the unit tests under Phantom)
- [ ] Running `grunt browserify:watchTest` and loading the tests in-browser shows everything passing.
- [ ] Installing pileup.js as an NPM package and then doing `var pileup = require("pileup")` results in a functional pileup viewer (e.g. in Cycledash)
- [ ] Sourcing `pileup.min.js` results in a global `pileup` object for those who don't want to use Browserify.

[1]: https://github.com/hammerlab/pileup.js/issues/200
