### ISSUE TITLE
Pileup.js doesn't load BAMs in Safari

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/pileup.js#192]
When I try to inspect a variant in Safari, pileup hangs and doesn't load the BAM files.

**Comment by jaclynperrone** [comment]
Same goes for viewing the demo on http://localhost:8080/examples/playground-complete.html. It just hangs in Safari:

![screen shot 2015-07-02 at 11 58 36 am](https://cloud.githubusercontent.com/assets/5685044/8481558/bc93b41a-20b1-11e5-8dc3-fddaca9bac3e.png)

**Comment by ihodes** [comment]
```
[Error] TypeError: undefined is not an object (evaluating 'header.sequences.map')
	(anonymous function) (pileup.js, line 23897)
[Error] TypeError: undefined is not an object (evaluating 'twoBitHeader.chromosomeTree.nodes.contents')
	(anonymous function) (pileup.js, line 23897)
[Error] TypeError: undefined is not an object (evaluating 'header.sequences.map')
	(anonymous function) (pileup.js, line 23897)```

**Comment by ihodes** [comment]
So, Safari 9.0 passes 
![screen shot 2015-09-30 at 6 03 00 pm](https://cloud.githubusercontent.com/assets/167803/10207936/9db7ba54-679d-11e5-9514-e5b66539a5af.png). Done & done.
