### ISSUE TITLE
Move the pileup window controls below the table header

### ISSUE THREAD

**Issue by jaclynperrone** [hammerlab/pileup.js#193]
Keeping them above the table header looks a little awkward. If we move them below, as seen in the mockup, the transition and layout will look a little more seamless. And the pileup will look like it's sitting in the table, rather than on a different page. 

![move-controls](https://cloud.githubusercontent.com/assets/5685044/8170665/6899cf86-1380-11e5-9613-dcee466347db.png)

**Comment by jaclynperrone** [comment]
And I'll add some styles that make those controls a little more apparent.

**Comment by danvk** [comment]
This is more of a Cycledash issue. @jaclynperrone if you want to take a stab at this, it should just be a matter of rearranging lines here: https://github.com/hammerlab/cycledash/blob/1d31a7582475907c34e64b11e82fc8e392840df0/cycledash/static/js/examine/components/PileupViewer.js#L63-L71

**Comment by jaclynperrone** [comment]
Will do!
