### ISSUE TITLE
"Required module not found" Flow errors

### ISSUE THREAD

**Issue by winkler1** [hammerlab/pileup.js#200]
It's really cool that you're using Flow so heavily in this. Getting errors though--

$ grunt travis
Running "flow:app" (flow) task
>> /Users/Jeff/repos/ghtemp/src/BamDataSource.js:12,8,11: Unexpected token type
>> 
>> /Users/Jeff/repos/ghtemp/src/BigBed.js:16,22,48: ContigInterval.js
>> Required module not found
>> 
>> /Users/Jeff/repos/ghtemp/src/BigBedDataSource.js:9,22,48: ContigInterval.js
>> Required module not found
>> 
>> /Users/Jeff/repos/ghtemp/src/ContigInterval.js:12,23,23: Unexpected token :
>> 
>> /Users/Jeff/repos/ghtemp/src/Controls.js:25,35,48: identifier SyntheticEvent
>> Unknown global name
>> 
>> /Users/Jeff/repos/ghtemp/src/Controls.js:39,23,61: call of method indexOf
>> Method cannot be called on possibly null or undefined value
>>   /Users/Jeff/repos/ghtemp/src/Controls.js:14,17,63: ?arrayOf
>> 
>> /Users/Jeff/repos/ghtemp/src/Controls.js:66,11,85: call of method map
>> Method cannot be called on possibly null or undefined value
>>   /Users/Jeff/repos/ghtemp/src/Controls.js:14,17,63: ?arrayOf

**Comment by danvk** [comment]
@winkler1 thanks for trying pileup.js! Can you check which version of Flow you're using?

The three "Required module not found" errors are a known issue. @armish is there an easy workaround available for this before we address #188? We're in a state that's a bit confusing for new users.

I only see three errors when I run `grunt travis`, not 81!

```
grunt travis
Running "flow:app" (flow) task
>> /Users/danvk/github/pileup.js/test/GenomeTrack-test.js:14,14,30: pileup
>> Required module not found
>>
>> /Users/danvk/github/pileup.js/test/PileupTrack-test.js:16,14,30: pileup
>> Required module not found
>>
>> /Users/danvk/github/pileup.js/test/components-test.js:6,14,30: pileup
>> Required module not found
>>
>> Found 3 errors
Warning: Task "flow:app" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by winkler1** [comment]
Ah... I tend to forget not everything runs from /node_modules :) Bad version was `0.1.2`.  With `0.12.0`, get the same 3 errors you have. Thanks.

ES6 with Flow: looks like you avoided unsupported things like `const`, and didn't have to use any [workarounds](http://www.keendevelopment.ch/flow-babel-gulp-es6/) to get them to play together?

**Comment by danvk** [comment]
I'm surprised that `grunt travis` used your system-wide `flow` binary, rather than the one in pileup's `node_modules` directory. I added `./node_modules/.bin` to my `PATH` and have been pretty happy about it.

We've been using Facebook's jstransform for ES6 rather than Babel. I believe that jstransform and Flow use the same ES6 parser internally, so this makes it easy to keep things in sync. We've been using a fairly conservative subset of ES6: no `let`, `const`, generators, etc. It would be great if Flow supported `const`! (https://github.com/facebook/flow/issues/266)
