### ISSUE TITLE
Layout discrepancies in Firefox

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#221]
Here's what the demo page looks like in Firefox:

![pileup firefox](https://cloud.githubusercontent.com/assets/98301/8575632/fc51249e-256a-11e5-892b-0ecbec17afd2.png)

The gene track is significantly larger than it is in Chrome:

![pileup chrome](https://cloud.githubusercontent.com/assets/98301/8575643/0c997b4e-256b-11e5-8a6f-601ce1ce5d4b.png)

cc @jaclynperrone

**Comment by jaclynperrone** [comment]
Noticed that, too!

**Comment by jaclynperrone** [comment]
For some reason there's an extra 100px added to the height of that svg in Firefox.

**Comment by danvk** [comment]
This seems to have gone away:

<img width="999" alt="pileup firefox" src="https://cloud.githubusercontent.com/assets/98301/10175850/462dfade-66bf-11e5-875e-116d05f47e89.png">

@jaclynperrone maybe you fixed it? Or maybe the `<canvas>` transition fixed it. Either way, this is no longer a problem.
