### ISSUE TITLE
Show mismatches in CoverageTrack

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#233]
The coverage track can give a quick overview of how strong the evidence for a variant is.

**Comment by armish** [comment]
![screen shot 2015-09-14 at 6 04 57 pm](https://cloud.githubusercontent.com/assets/7809/9863104/231a7762-5b0b-11e5-93b7-669ad089c3e6.png)

**Comment by danvk** [comment]
Here's what [igv.js][1] looks like rendering this:
<img width="545" alt="screen shot 2015-10-13 at 11 04 45 am" src="https://cloud.githubusercontent.com/assets/98301/10458729/41c74258-719a-11e5-82c4-a46dce5ace7a.png">

[1]: http://exac.broadinstitute.org/variant/1-55505520-G-A
