### ISSUE TITLE
Reference track color blocks shouldn't have whitespace when zoomed out

### ISSUE THREAD

**Issue by ihodes** [hammerlab/pileup.js#274]
It creates a sort of scintillating effect; would look a little less busy if the block of color were solid.

![](https://cloud.githubusercontent.com/assets/167803/10108784/0bcd9b96-6391-11e5-874d-feaee63cdd35.png)

**Comment by danvk** [comment]
Same as #226

**Comment by danvk** [comment]
@ihodes I remember you wrote some code for this. Did you want to send out a PR for it? I'm fine with the color changes.

**Comment by ihodes** [comment]
I wasn't able to resolve resolution-dependent issues in a satisfactory way, unfortunately.

**Comment by danvk** [comment]
Resolution independence is baked in now (see #285), so maybe that's no longer an issue?

**Comment by ihodes** [comment]
Maybe? I certainly wasn't testing on retina displays, so I'm not sure. I'll try to swing back around to it & see if I can get this closed.

**Comment by danvk** [comment]
@ihodes I noticed that IGV.js has solid blocks of color, both for the reference & coverage tracks. Would be great to get your changes merged in here, I don't think there were any remaining blockers. (I'm happy to let you test on my retina screen if it helps)

![screen shot 2015-10-26 at 4 13 11 pm](https://cloud.githubusercontent.com/assets/98301/10741119/795aeadc-7bfc-11e5-8d6c-cf0f24d7ed0d.png)
