### ISSUE TITLE
Optimize extractSummaryStatistics

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#324]
When I zoom far out (say to 11,000 bp) and pan, the `extractSummaryStatistics` method becomes a dominant (90+% of cycles) hotspot:

![screen shot 2015-10-22 at 3 57 08 pm](https://cloud.githubusercontent.com/assets/98301/10676665/c3663700-78d5-11e5-9c2a-1c784e08abc0.png)

Optimizations to that or to `getOpInfo` would go a long way. Alternatively, we could find a way to cache some of this computation. Once we have both reference data & alignment data, we should only ever have to compute stats for that read once.

**Comment by armish** [comment]
Just mind-storming for future exploration:

One quick way to optimize this for longer ranges would be to calculate coverage on representative bases within a genomic window. For example, we can set the maximum number of bins to be displayed to 1000 and for 11kbp window we can sample one base within 11bp windows. Coverage tends to follow a smooth, bell-shaped-like curve over adjacent bases; so this approach can be a good heuristic for larger genomic views.

**Comment by danvk** [comment]
I'm not sure if sampling in that way would make much of a difference—you'd still have to iterate over all of the reads and get every 11th base pair.

I was thinking more along the lines of keeping a cache of {locus→depth} and {locus→mismatches}. Then when new reads come in, you can add just the new ones to the cache, rather than recalculating the whole thing (as `CoverageTrack` does now).

**Comment by danvk** [comment]
@armish think you'll have a chance to look into this one? I'll probably drop it from the 0.6.0 milestone if not.

**Comment by armish** [comment]
probably not this week :( If you are planning to cut a release soon, feel free to drop it and I will get back to it for the next release.

**Comment by danvk** [comment]
This is very noticeable if you open the new `structural-variants.html` demo and pan:

![screen shot 2015-11-12 at 11 49 45 am](https://cloud.githubusercontent.com/assets/98301/11124549/994e1820-8933-11e5-8036-05b96ab8ceb8.png)
