### ISSUE TITLE
Misaligned reads

### ISSUE THREAD

**Issue by ihodes** [hammerlab/pileup.js#399]
Repro: loaded up a BAM using pileup 0.6.1, scrolled to the right:

![](https://s3.amazonaws.com/f.cl.ly/items/253Y1Q3x3Z0F0F3h3c2Q/Screen%20Shot%202015-12-17%20at%202.31.14%20PM.png?v=1578da47)

**Comment by danvk** [comment]
Is this in cycledash? Did you upgrade the version of pileup in cycledash?
(I fixed something that looked identical to this a few weeks back.)

**Comment by ihodes** [comment]
I did upgrade (as noted, to 0.6.1, that appears to be the newest?)

**Comment by danvk** [comment]
Hmm, you sure the new copy made it in? (did you "gulp prod"?) do you see
the gear icon next to the pileups?

**Comment by ihodes** [comment]
Yep, definitely on that one: http://link.isaachodes.io/2i3O2w180H1R

**Comment by danvk** [comment]
@ihodes I think we resolved this, right? There were pileup commits that hadn't been released yet?

**Comment by ihodes** [comment]
I don't recall; I'll close it though, and we can always reopen it.
