### ISSUE TITLE
Question about the "ensGene.bb" file from the demo

### ISSUE THREAD

**Issue by robinandeer** [hammerlab/pileup.js#401]
Hi,

I'm trying to setup an instance of pileup.js - great package btw!

I was using the `ensGene.bb` file from the online demo but noticed that the gene coordinates were off from what I expected. Are you using GRCh38? In any case, I was wondering how you guys but the original BED file together?

Which columns are really necessary to display the gene with HGNC symbol (and perhaps exons) in the viewer?

**Comment by danvk** [comment]
The `ensGene.bb` file comes from Dalliance. You'd have to ask Thomas how he assembled it.

The expected format is described [here][1] and you can see how pileup.js uses it [here][2]. Looking at that code, it seems that the required columns are:

- 1-3 (the range)
- 4 (Gene ID)
- 6 (strand)
- 7+8 (the coding region)
- 11+12 (comma-separated list of exon lengths and starting offsets)
- 13 (a different gene ID)
- 14 (human-readable gene name)

Let me know if that makes sense. I'm happy to hear that you've enjoyed pileup. Curious to hear how you discovered it!

[1]: http://genome.ucsc.edu/FAQ/FAQformat#format1
[2]: https://github.com/hammerlab/pileup.js/blob/962625e2c984a86da2f9e1eb55febece1004ba67/src/main/sources/BigBedDataSource.js#L34-L55

**Comment by robinandeer** [comment]
Thank you!!

I was able to create a BigBed file using a Biomart export that I messed around with

I don't remember quite how I found about about pileup.js but I was looking at other tools like IGV.js and pybamview but they didn't fit our usecase as well as pileup :wink: I was probably looking around GitHub I would guess

**Comment by danvk** [comment]
Glad this worked out for you! I'll go ahead and close the issue.

**Comment by agentm** [comment]
The fact remains that ensGene.bb doesn't match the actual genes for hg19 as used in `examples/index.html`. The ensGene.bb gene track is likely not for hg19, so it makes for a poor demo of pileup's abilities. For example, `chr17:7577534` is not displayed on `TP53` as in the [UCSC Hg19 Genome Browser](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr17%3A7577534%2D7577534&hgsid=654021743_dB4uaO32zI6ksa7wHD9cMDeiGqTR).

In addition, I found incompatibility between pileup and existing `bb` files such as [this one](http://hgdownload.cse.ucsc.edu/gbdb/hg19/knownGene.bb). A `RangeError` is thrown while trying to read the header, apparently related to an unexpectedly empty `zoomLevel` array.

Like the original reporter, I also needed to create a valid hg19 gene track, but I am completely new to bioinformatics, so here are some instructions for other users who may be in the same boat:

1. Use UCSC Table Browser to download Hg19 RefSeq Genes/refGene table selecting specific columns such as exons and including `hg19.refGene`'s `name2` column to create `x.tsv` specific to the genome (`bed` is a tab-separated, line-oriented format)
1. Use spreadsheet application to re-order the columns to match the [BED spec](http://genome.ucsc.edu/FAQ/FAQformat#format1) (score and rgb columns are unused and can be set to "0")
1. in addition to the 12 standard columns, pileup expects two additional columns: alternate gene id (not displayed, not important) and the refseq gene name (displayed- `name2` from table)
1. create a script to:
   * convert `blockStarts` to be relative to the gene start
   * convert `blockEnds` to `blockSizes` (end - start)
1. run `bedSort x.tsv x.tsv` to prepare for bigbed indexing
1. run `fetchChromSizes` to download the genome chromosome sizes for the specific genome in question
1. run `bedToBigBed -type=bed12+2 x.tsv hg19.chrom.sizes x.bb`

I am happy to provide the `bb` file I created with the instructions above to save other users the headache.
