### ISSUE TITLE
Add a JSON format

### ISSUE THREAD

**Issue by ihodes** [hammerlab/pileup.js#409]
It'd be nice if you could pass an array JSON representing [ThinAlignments](https://github.com/hammerlab/pileup.js/blob/master/src/main/data/formats/bamTypes.js#L21) to Pileup.js  and have it display those. 

Use case: display pileups in iPython notebooks.

**Comment by armish** [comment]
this is also relevant: #297

**Comment by danielecook** [comment]
Along these lines, it'd be great to have the ability to fetch data from a server (e.g. ajax call) and trigger updating of a track when the browser is scanned/zoomed.

**Comment by armish** [comment]
hi @danielecook — thanks for your comment! 

Can you elaborate on your point a little bit more? I am asking this because that is what pileup.js is doing right now: it works with ranges and only pulls data in when it is needed (for example if you zoom out and pileup.js needs to grab more from the reference sequence or bam). 

This is a bit trickier to accomplish with a JSON data source and we still haven't thought of a quick solution to this.

**Comment by danielecook** [comment]
@armish sure!

The issue I have right now is that I'm having trouble showing variant data from a large VCF. I have all the variant data in a database, however. And It's much easier for me to write a rest interface for fetching variants and putting them in any JSON format that would be required (ideally, Chrom, start, stop, and possibly color/data attributes). 

So the basic idea would be for the user to either specify a REST URL for the data source that would be fairly strait forward (e.g. `api/chrom/start/stop`), or allow the user to bind events to the canvas object so they can update a track with the appropriate data fetched from the server whenever they move pan/zoom.

Does this make sense?

Thanks

**Comment by armish** [comment]
Yepp, this definitely makes sense. Thanks for the details! If we go with the JSON option, we should pass those range arguments  to the server and let it handle those optionally. 

I also had in mind to support indexed (e.g. tabix'ed) VCF files and gzipp'ed ones as you suggested earlier in #404, where we can work those range requests out in a proper way. I wonder if there is a way to index JSON files in a similar way (TODO for me).

**Comment by danvk** [comment]
Ideally your REST API would be GA4GH's.

**Comment by akmorrow13** [comment]
Closed via https://github.com/hammerlab/pileup.js/pull/460
