### ISSUE TITLE
pileup.js (difficulties to load susScr3.2bit)

### ISSUE THREAD

**Issue by marcguellc** [hammerlab/pileup.js#410]
Hey,
I'm experiencing difficulties to load our .2bit file ([susScr3](http://hgdownload.cse.ucsc.edu/goldenPath/susScr3/bigZips/susScr3.2bit)). See my data.js below. I have no problem in loading any of the test .2bit files( test.2bit, http://www.biodalliance.org/datasets/hg19.2bit). I cannot understand what is the problem. I'd would really appreciate any advice. This is the error I get:

![image 6](https://cloud.githubusercontent.com/assets/3690357/15075102/9f521e48-1370-11e6-8734-bd26928a1b18.png)

Thanks a lot!

my data.js file

```
# Some data for the demo.

var sources = [
  {
    viz: pileup.viz.genome(),
    isReference: true,
    data: pileup.formats.twoBit({
      url: 'http://hgdownload.cse.ucsc.edu/goldenPath/susScr3/bigZips/susScr3.2bit'
    }),
    name: 'Reference'
  },
  {
    viz: pileup.viz.scale(),
    name: 'Scale'
  },
  {
    viz: pileup.viz.location(),
    name: 'Location'
  }
];

var range = {contig: 'chr1', start: 1, stop: 1000};
```

**Comment by armish** [comment]
Thanks a lot for reporting this problem, Marc! Since our 2bit parser was built from bottom up, we sometimes have edge cases that we have never thought of. Sorry that you hit one such case.

I will take a closer look at how to fix this in a few days and will make a new release. Will also update this thread as soon as I am done. Stay tuned.

**Comment by armish** [comment]
@marcguellc: OK, this should be fixed with the newest version of the pileup.js: [v0.6.5](https://www.npmjs.com/package/pileup). You can update your working copy via `npm update pileup`.

Thanks again for reporting this issue and please let me know if have trouble getting this to work.
