### ISSUE TITLE
Way to force rendering of pileup component

### ISSUE THREAD

**Issue by piotr-gawron** [hammerlab/pileup.js#414]
I'm writing quite complex application. I was planning to use pileup.js for vizualization gene variants data. However, I encountered some rendering issues when creating pileup object before attaching it to DOM.

For instance, the code below will not render properly:

``` javascript
var element = document.getElementById('pileup');

var newElement = document.createElement("div");

var p = pileup.create(newElement, {
  range: range,
  tracks: sources
});

element.appendChild(newElement);
```

The reason (as far as I understand) is that when pileup object is created the newElement doesn't belong to DOM, so it's not intialized/rendered. This make sense - it's a performance issue. However, when I add newElement to the DOM I expect the object to be initialized and rendered properly, but it doesn't happen. Is there a method that I can call to force rendering? Or can this issue be fixed in any other way?

The only workaround that I found is to trigger resize event on window object:

``` javascript
window.dispatchEvent(new Event('resize'));
```

but this might not be a cross-brower approach (I checked it only on firefox 46.0.1 and chrome 50.0.2661.102)

Here is a jsfiddle that visualizes the problem: http://jsfiddle.net/40ygmtd8/5/

**Comment by danvk** [comment]
It probably is rendered, it's just that unstyled `div`s have zero height. There's no way that I'm aware of for a JS library to learn about its `div` being resized (the Google Maps API has the same issue, for example). So dispatching a resize event isn't a bad workaround. Or perhaps pileup could expose a `resize()` method of its own.

**Comment by piotr-gawron** [comment]
Hm... I thought the same and I did some tests: I created a div with fixed size, but I got the same result:

tak a look here: 
http://jsfiddle.net/40ygmtd8/6/ (the div width and height are: 500px)

When you investigate elments in chrome or firefox you will see that canvas elements (used for visualization) have non zero width, height, but there is no content and the size is different.

Anyway, I found this rendering issue also in other situations, so it would be nice to have a method that would force pileup to re-render everything.

**Comment by piotr-gawron** [comment]
I think the source of this issue is that in tracks (GeneTrack.js, GenomeTrack.js, etc.) the component where content is visualized is retrieved using: [ReactDOM.findDOMNode](https://facebook.github.io/react/docs/top-level-api.html#reactdom.finddomnode) method. This will not work if a div where we want to visualize our data is not in a DOM.
