### ISSUE TITLE
Confirm pileup file structure changed

### ISSUE THREAD

**Issue by pvnr0082t** [hammerlab/pileup.js#431]
Hi @danvk ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. Because pileup v0.6.7 changed the structure and caused the auto-updater in cdnjs fetched something we can not use directly, we modify auto-update config for pileup. Could you please take a look at the [config change](https://github.com/cdnjs/cdnjs/pull/8486/files)? Thank you.

https://github.com/cdnjs/cdnjs/issues/8454
https://github.com/cdnjs/cdnjs/pull/8486

**Comment by danvk** [comment]
@armish did 0.6.7 change the file structure?

**Comment by pvnr0082t** [comment]
I think file structure changed from v0.6.1.

**Comment by armish** [comment]
@danvk: the major change happened earlier on (v0.4.0), but looks like we moved some of the files around in `v0.6.2`, too; but that last one didn't change the final compiled files @pvnr0082t. We distribute `main` and `test` folders, too; but I don't think people will be interested in accessing those through CDN. 

Here is a list of files that we are interested in distributing:

- dist/pileup.js
- dist/pileup.js.map
- dist/pileup.min.js
- dist/pileup.min.js.map
- dist/style/pileup.css

Let me know if I can help, @pvnr0082t.

**Comment by armish** [comment]
@pvnr0082t: assuming that this confirmation went through, I am closing this issue. Feel free to re-open it if you need more details on this.

Thanks!
