### ISSUE TITLE
Uncaught Gzip error: incorrect header check

### ISSUE THREAD

**Issue by AndyBlake** [hammerlab/pileup.js#432]
Using the simple example I tried loading one of my own bams with the bai and I get this error - any idea what I'm doing wrong?
Sorry for the bother.
Andy

**Comment by armish** [comment]
Hi Andy,

Argh — this seemed to fall through the cracks :( Were you able to resolve this issue after all? If you can provide us with a sample BAM/BAI to reproduce this error, I am more than happy to fix this in the main code base. 

Temporarily closing this issue, but feel free to re-open if you are still interested in following up on this.
