### ISSUE TITLE
Pileup error in Chrome

### ISSUE THREAD

**Issue by ifll** [hammerlab/pileup.js#437]
I have found an error while using pileup.js in Chrome in Ubuntu while running pileup.js with the following code:

``` javascript
window.divGB = document.getElementById('genomeBrowserHolder');
window.range = {contig: 'chr17', start: 7512384, stop: 7512544};
window.bamSource = pileup.formats.bam({
        url: "URL/myfile.bam",
        indexUrl: "URL/myfile.bam.bai"
    });
window.sources = [
      {
          viz: pileup.viz.genome(),
          isReference: true,
          data: pileup.formats.twoBit({
            url: 'http://www.biodalliance.org/datasets/hg38.2bit'
          }),
          name: 'Reference'
      },
      {
          viz: pileup.viz.scale(),
          name: 'Scale'
      },
      {
          viz: pileup.viz.location(),
          name: 'Location'
      },
      {
          viz: pileup.viz.coverage(),
          data: bamSource,
          name: 'Coverage'
      },
      {
          viz: pileup.viz.pileup({
            viewAsPairs: true
          }),
          data: bamSource,
          cssClass: 'normal',
          name: 'Alignments'
      }
    ];
window.p = pileup.create(divGB, {
          range: range,
          tracks: sources
        });
```
-  I am using "Chromium web browser" version 52.0.2743.116
-  I am using Ubuntu 16.04
-  I am using the latest version of Pileup.js
-  The error only appears on Chrome, as in Mozilla 48.0 (latest mozilla) there is no such error.
-  The error on Chrome only appears when cache is enabled. If cache is disabled, using _"Chrome's developer tools -> Network tab"_ to check it the error doesn't appear

The error says the following:

```
TwoBit.js:165  ->  Error name: RangeError
q.js:161  ->  Uncaught Couldn't parse the header from the first 2097152 bytes of the file. Corrupted 2bit file?
```

Am I doing something Wrong? Is this version of Chrome doing something wrong? Is there a bug in Pileup.js?

Thank you very much!!

**Comment by armish** [comment]
Thanks for including all the details, @ifll!

To test this issue: I spun a new Ubuntu 16.04 VM from scratch, installed the latest Chromium on it and tried to run pileup.js against the same TwoBit file you have in your configuration (`http://www.biodalliance.org/datasets/hg38.2bit`) - looks like all works well in my case:

```
~/tmp/pileup.js$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

![Chromium version](https://d3vv6lp55qjaqc.cloudfront.net/items/1v2t2b0P0p1V3O250X13/Image%202016-09-21%20at%201.15.56%20PM.png?X-CloudApp-Visitor-Id=1759383)
![Pileup demo](https://d3vv6lp55qjaqc.cloudfront.net/items/0o103t0O1z0723054035/Image%202016-09-21%20at%201.15.43%20PM.png?X-CloudApp-Visitor-Id=1759383)

The same goes for my mac laptop that has the same exact Chrome version installed on it.

Do you think this might be a temporary issue with the network/biodalliance server you are running the pileup.js against? Would love to replicate this issue but having trouble with it. 

One thing you might try is to download the 2bit file to your local and run pileup.js against that to increase the network/server reliability on your end. Hopefully, that will solve your issue.

**Comment by ifll** [comment]
Hi @armish 
I have also tried with storing the file locally and I keep having the same trouble...

As it is working on mozilla like charm I am not really worried about this issue, but I will try to uninstall and install again Google Chrome on ubuntu 16.04 to check if there was any trouble on the installation, as it seems it might be a problem of Chrome cache as when it is disabled it works. I will let you know about this.

Besides, did you check if you had cache enabled on chrome when you were doing this trials? Because if cache is disabled by default then it also works on my computer.

Thank you for the support on this issue and for you advice!

**Comment by armish** [comment]
To be honest, I didn't check whether I had the caches disabled or not; but they should be enabled by default out of the box, right?

Hopefully, this issue is isolated to a specific version of the Chrome on a specific version of the platform. For now, I am closing this issue as we weren't able to replicate this on a relatively new setup.

Thanks for all the help!
