### ISSUE TITLE
Add Chromosome position

### ISSUE THREAD

**Issue by ifll** [hammerlab/pileup.js#438]
This is an enhancement for the application.

It would be great if there was a track which could show at which position you are zoomed in on the chromosome. Such as Ensembl has:

![screenshot1_1](https://cloud.githubusercontent.com/assets/16896039/18750270/be9eaa00-80da-11e6-9ef8-6302dd342622.png)
-  In the previous image In Purple it is highlighted the track I am mentioning
-  This track has a red square on the position where you are located
-  It also gives other information of the chromosome. In my opinion, if it were possible to show only the starting and ending positions of this chromosome it would be enough

I think this is quite important for the user not to be lost inside the chromosome and to have an idea about which region is being watched

**Comment by armish** [comment]
thanks for the suggestion, @ifll! 

It is a bit out-dated, but if you are interested in using one of our (somewhat old) libraries, you can check out [idiogrammatik](https://github.com/hammerlab/idiogrammatik). We still haven't integrated it with pileup.js, though.

Will keep this issue open as a possible enhancement option.

**Comment by ifll** [comment]
I will give it a look, it looks interesting.

Thank you very much!

**Comment by akmorrow13** [comment]
Addressed with https://github.com/hammerlab/pileup.js/pull/537
