### ISSUE TITLE
Canvas for Coverage and Alignment cut short

### ISSUE THREAD

**Issue by Georgehe4** [hammerlab/pileup.js#439]
<img width="1237" alt="screen shot 2016-10-10 at 9 38 35 am" src="https://cloud.githubusercontent.com/assets/3150228/19243729/a237e592-8ecd-11e6-9960-be0513cfb3a4.png">

The bottom of the canvas elements for coverage and alignment are cut short. The minimum read depth of the coverage elements in the screen shot (taken from examples/index.html) is around 30, not 0 as the image would indicate.

**Comment by armish** [comment]
thanks for reporting this issue, @Georgehe4!

I will take a look what might be going wrong by the end of this week; but in the meantime, do you think you can provide us with some sample data to reproduce this error? Also your browser/platform information would really be useful for debugging purposes.

Thanks!
-- Arman

**Comment by armish** [comment]
@Georgehe4: having trouble replicating this issue on my current set of setups. Would you mind providing an example data and/or OS/Browser specs for me to see what might be going wrong?

**Comment by Georgehe4** [comment]
Updating as this issue its impact is growing.

When I visit the demo link at http://www.hammerlab.org/pileup/, the issue pops up
I am running chrome on version 57.0.2987.133 (64-bit) on OS X El Capitan 10.11.6.

<img width="1269" alt="screen shot 2017-04-24 at 9 57 15 pm" src="https://cloud.githubusercontent.com/assets/3150228/25365772/0cc5c8d8-2939-11e7-9c9e-fbcc385bccd8.png">
