### ISSUE TITLE
REST API and documentation

### ISSUE THREAD

**Issue by pavelber** [hammerlab/pileup.js#445]
I want to include pileup to the my site to analyze VERY large bam files.
Is there a way (REST API) to provide data for a range instead of loading the whole track?
If it is possible, I would like to write my own server, which will parse bam files in advance and will provide to the client side (pileup) data for a visible range

**Comment by armish** [comment]
Hi @pavelber — there is an ongoing discussion on some potential solutions to your issue under #444 and #403. Hope this helps.

**Comment by pavelber** [comment]
Hi, @armish - CGI is the right direction, but I prefer to be able to write completely my own server side, which will implement some API. As I see it is not possible yet, correct?

**Comment by armish** [comment]
@pavelber: we do have experimental support for transferring bits of BAM files using the GA4GH protocol, which might be of interest to you since it is server-side agnostic as long as it is compatible with the protocol.

**Comment by pavelber** [comment]
Great! Where can I read documentation about this?

**Comment by armish** [comment]
Here is the specific data source implementation: https://github.com/hammerlab/pileup.js/blob/0182b225205e52e1489727004d69e84442eafb88/src/main/GA4GHAlignment.js

here are the tests that might help you get started: 
https://github.com/hammerlab/pileup.js/blob/0182b225205e52e1489727004d69e84442eafb88/src/test/GA4GHAlignment-test.js

and here is a test file to test the protocol: 
https://github.com/hammerlab/pileup.js/blob/0182b225205e52e1489727004d69e84442eafb88/test-data/README.md#chr171-250bam-chr171-250json
