### ISSUE TITLE
A gene named null

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#45]
At chr17:7464586-7467146

![screen shot 2015-03-17 at 11 29 38 pm](https://cloud.githubusercontent.com/assets/98301/6702159/8e2bdf10-ccfd-11e4-9e6d-c2d0b3adf700.png)

**Comment by danvk** [comment]
I don't see this any more.

**Comment by superbobry** [comment]
I've found a way to reproduce this with the latest `master`: open `examples/index.html` and click zoom out ("-") until nulls start to appear. 

Here's an example:

![image](https://cloud.githubusercontent.com/assets/185856/19484044/f025630a-955e-11e6-8fd4-71466fe0f38f.png)

**Comment by armish** [comment]
thanks @superbobry - I have intermittent internet access this week, but will look into this next week :+1:

**Comment by akmorrow13** [comment]
Fixed with https://github.com/hammerlab/pileup.js/pull/488
