### ISSUE TITLE
How are the props height and width set for viz elements?

### ISSUE THREAD

**Issue by akmorrow13** [hammerlab/pileup.js#452]
I am struggling to change the height of the wrapper for viz elements (ie. PileupTrack, GeneTrack, etc). The constructor takes in VizProps type, which contains the height (see https://github.com/hammerlab/pileup.js/blob/master/src/main/viz/PileupTrack.js#L254). However, I cannot find where the height for this props element is set. It seems to be different for all tracks.

**Comment by armish** [comment]
We have some default widths/heights set within the `pileup.css` ([example](https://github.com/hammerlab/pileup.js/blob/master/style/pileup.css#L219)). You can override those settings by your own CSS rules and they are passed down to the actual visualization elements.

Hope this helps.

**Comment by akmorrow13** [comment]
Thanks @armish!
