### ISSUE TITLE
Display names on tracks

### ISSUE THREAD

**Issue by akmorrow13** [hammerlab/pileup.js#456]
Would pileup be interested in a PR that adds file names to the track content? Currently, only 'Variant' or 'Alignment is displayed (see here)
![screen shot 2017-05-08 at 2 25 21 pm](https://cloud.githubusercontent.com/assets/6503416/25821340/55d00d24-33fa-11e7-81b6-585c93a47840.png)

Ideally, we would display the file name. 

Tagging @Georgehe4

**Comment by armish** [comment]
@akmorrow13 @Georgehe4: actually, this is already doable via passing a `name` attribute to the track object, e.g.: https://github.com/hammerlab/pileup.js/blob/master/examples/structural-variants.js#L28 -> 

When those are not passed, pileup.js uses the default one — `Alignments` and `Variants` in your case.
