### ISSUE TITLE
How do you use pileup.js in an ASP.Net app?

### ISSUE THREAD

**Issue by IDispose** [hammerlab/pileup.js#461]
Is pileup.js designed to be used only in a nodejs app? 

It appears the several paths in pileup.js are hardcoded to look for specific supporting files (for example I saw ../data/bam as an argument to a require statement). 

How do I use pileup.js in an ASP.Net web app? 

Any directions highly appreciated.

**Comment by chgibb** [comment]
From the readme:


To use pileup.js in a project, install it via NPM:

```npm install --save pileup```
And then source either ```node_modules/pileup/dist/pileup.min.js``` or ```pileup.js```.

Which file you choose (dev vs prod) and how you source it (```<script>``` vs some kind of bundler) is up to you.

**Comment by IDispose** [comment]
@chgibb Thanks for responding

Yes, I followed the instructions. Then copied over pileup.js to my simple asp.net app and am referencing the js file via a simple script tag.

**Comment by chgibb** [comment]
No worries @IDispose .
What you have there looks good. Are you still having issues?

**Comment by IDispose** [comment]
@chgibb 
I have sorted the issues. It's working now. Thanks for your responses.

**Comment by chgibb** [comment]
No worries @IDispose. Good to hear you figured it out.
