### ISSUE TITLE
How do you use index chunks to speed up BAM retrieval?

### ISSUE THREAD

**Issue by IDispose** [hammerlab/pileup.js#462]
The Alignments section of my web page displays the message

"Loading alignments (Fetching BAM Index -- use index chunks to speed this up)"

So how do you use index chunks? What am I missing? 

Thanks

**Comment by armish** [comment]
Hi @IDispose - sorry, I thought I replied to this but apparently didn't. Are you still having this issue? If so, thsoe chunks are coming from the index file `yourfile.bam.bai` which is assumed to be served from the same location with your BAM file by default. Do you think you might be missing that?
