### ISSUE TITLE
update to current GA4GH schema

### ISSUE THREAD

**Issue by jpdna** [hammerlab/pileup.js#469]
The JSON that pileup.js expects as described in the example at:
https://github.com/hammerlab/pileup.js/blob/master/test-data/alignments.ga4gh.chr17.1-250.json
is based on an older version of the GA4GH schema.

Pileup.js should be updated to make use of the current GA4GH schema version '0.6.0a10-SNAPSHOT` described here: https://github.com/ga4gh/ga4gh-schemas/blob/master/pom.xml

Differences include (but may not be limited to) for alignments

- `properPlacement` changed to `improperPlacement`
- Position record type now specifies `strand` via new enum Strand (in place of boolean `reverseStrand`).
-Replaced `info` fields with rich type `Attributes` fields

these changes and others are described in the [changelog](https://github.com/ga4gh/ga4gh-schemas/blob/53a4da698d1800721a451701df018af8178fa083/doc/source/changelog.rst)

mentioning @akmorrow13

**Comment by akmorrow13** [comment]
Resolved with https://github.com/hammerlab/pileup.js/pull/470
