### ISSUE TITLE
Simple17.bb fails to display with `Cannot read property 'replace' of undefined`

### ISSUE THREAD

**Issue by denisemauldin** [hammerlab/pileup.js#477]
When loading a simple bigBed file that doesn't contain exon arrays, pileup.js throws an error.

Cannot read property 'replace' of undefined
    at parseBedFeature (BigBedDataSource.js:51)

```
function parseBedFeature(f): Gene {
  var position = new ContigInterval(f.contig, f.start, f.stop),
      x = f.rest.split('\t'),
      // exons arrays sometimes have trailing commas
      exonLengths = x[7].replace(/,*$/, '').split(',').map(Number),
      exonStarts = x[8].replace(/,*$/, '').split(',').map(Number),
      exons = _.zip(exonStarts, exonLengths)
               .map(function([start, length]) {
                 return new Interval(f.start + start, f.start + start + length);
               });

  return {
    position,
    id: x[0],  // e.g. ENST00000359597
    strand: x[2],  // either + or -
    codingRegion: new Interval(Number(x[3]), Number(x[4])),
    geneId: x[9],
    name: x[10],
    exons
  };
}
```

This is the config I'm using:

```
{
                    viz: pileup.viz.genes(),
                    data: pileup.formats.bigBed({
                      url: 'http://localhost:3000/assets/data/simple17.bb'
                    }),
                    name: 'Simple17'
                },
```

How do I load a bigBed file that only has `chrom, chromStart, chromEnd, name, score, strand`?

**Comment by denisemauldin** [comment]
I don't think it's the viz that's the problem.  I'm still getting the same error.  Is there a parser for regular bed files that isn't `pileup.formats.bigBed`?

**Comment by akmorrow13** [comment]
I think this could be fixed by adding a new function in BigBedDataSource.js called getGenesInRange(), which returns Genes, and getFeaturesInRange, which returns Features. FeatureTrack in range then would return features instead of Genes. With these changes the following should work:

{
                    viz: pileup.viz.features(),
                    data: pileup.formats.bigBed({
                      url: 'http://localhost:3000/assets/data/simple17.bb'
                    }),
                    name: 'Simple17'
                },

Is there anyway you can share the first couple lines of your file?

**Comment by akmorrow13** [comment]
https://github.com/hammerlab/pileup.js/pull/478/commits should allow this to work

**Comment by denisemauldin** [comment]
@akmorrow13 I was almost done (fixing the testing) with the PR I was making, so I submitted it just in case it was useful so we could chat about it!

**Comment by akmorrow13** [comment]
Fixed by https://github.com/hammerlab/pileup.js/pull/478
