### ISSUE TITLE
Issue with gene track when updating plot

### ISSUE THREAD

**Issue by kevinyao93** [hammerlab/pileup.js#498]
I'm not exactly sure what the problem is - this problem occurs when I switch between chr and positions. The Gene track data stops rendering after a few switches. I am currently using the pileup npm for react.
`    this.pileup.setRange({
      contig: chr,
      start: geneStart,
      stop: geneStop,
    });
`
Is what I'm currently trying to use, I have a plot chart with position and chr data that I'm using to decide the position the chart switches to, but it doesn't seem to work.

Also, I've been using the biodalliance gene track, and there seems to be a lot of null values, is there a better out there that I can use that works with pileup? It seems to only take bb values as well.

**Comment by akmorrow13** [comment]
Hi @kevinyao93 what version of pileup are you using? The most recent release should fix the NULL values. 

I am not sure why it is not rendering, there is not a lot of information here. My guess is that the canvas is not triggering to re-render.

**Comment by kevinyao93** [comment]
Sorry for the late update, ran into some issues earlier. I currently have pileup on version 0.6.10 but I still have null values
<img width="1268" alt="screen shot 2018-10-29 at 4 13 39 pm" src="https://user-images.githubusercontent.com/26494362/47677493-a46cbd80-db95-11e8-8c5c-612c38cea034.png">
These are the sources I've used to create the track.
```
const sources = [
  {
    viz: pileup.viz.genome(),
    isReference: true,
    data: pileup.formats.twoBit({
      url: 'http://www.biodalliance.org/datasets/hg19.2bit',
    }),
    name: 'Reference',
  },
  {
    viz: pileup.viz.scale(),
    name: 'Scale',
  },
  {
    viz: pileup.viz.location(),
    name: 'Location',
  },
  {
    viz: pileup.viz.genes(),
    data: pileup.formats.bigBed({
      url: 'https://www.biodalliance.org/datasets/ensGene.bb',
    }),
    name: 'Genes',
  },
  {
    viz: pileup.viz.variants(),
    data: pileup.formats.vcf({
      url: 'http://127.0.0.1:8091/deepsea.vcf',
    }),
    options: {
      variantHeightByFrequency: true,
    },
    name: 'Variants',
  },
];
```

**Comment by kevinyao93** [comment]
Sorry forgot to close this earlier, issue was resolved.
