### ISSUE TITLE
PileupViewer Genotype Visualization Error

### ISSUE THREAD

**Issue by abhim00** [hammerlab/pileup.js#530]
Genotypes which have a 0/0 type are displayed for some files and not others. In particular, it is showing up for this JSON file: https://github.com/hammerlab/pileup.js/blob/master/test-data/variants.ga4gh.chr1.10000-11000.json

You can view this file in a mango notebook with source=pileup.sources.GA4GHVariantJson()

**Comment by akmorrow13** [comment]
<img width="1271" alt="Screen Shot 2019-09-05 at 1 31 31 PM" src="https://user-images.githubusercontent.com/6503416/64378436-88ba1b00-cfe1-11e9-96a3-b7e89ecd20e9.png">

**Comment by akmorrow13** [comment]
closed with https://github.com/hammerlab/pileup.js/pull/531
