### ISSUE TITLE
programmatically creating screenshots

### ISSUE THREAD

**Issue by petermchale** [hammerlab/pileup.js#542]
Given a list of loci, and a set of tracks, is it possible to programmatically create thumbnails for each locus, i.e., without manually inspecting each locus in a browser? 

I am currently doing this in `igv.js` but it doesn't have an API that allows me to determine when all the data are loaded so that I can ensure that the screenshot is of a fully-rendered webpage, instead of one with "loading" icons on it, c.f., https://github.com/igvteam/igv.js/issues/1138 

Does `pileup.js` have an API that allows me to `await` for a complete webpage?

**Comment by akmorrow13** [comment]
Hi @petermchale, sorry for overlooking this! `pileup.js` has a function `toSVG()` that returns a `Promise<string>`. See here: https://github.com/hammerlab/pileup.js/blob/master/src/main/pileup.js#L193. Is this what you need?

**Comment by petermchale** [comment]
Possibly, but a better solution is probably to use https://bamsnap.readthedocs.io/en/latest/

**Comment by akmorrow13** [comment]
Sounds good, I will close this as the functionality is supported.
