### ISSUE TITLE
Only show one arrow in each intron

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#59]
This is how dalliance does it:

![screen shot 2015-03-20 at 5 15 25 pm](https://cloud.githubusercontent.com/assets/98301/6760990/be6e66e2-cf24-11e4-869f-bc35e569761b.png)

There was some preference expressed for this over the IGV behavior (arrow every N pixels) because it generates less chartjunk. (cc @hammer)

**Comment by hammer** [comment]
:100:

**Comment by hammer** [comment]
I expect these arrows will have to be adaptive to zoom level though to ensure we don't zoom into a region where the arrow has not been drawn. I'm sure you've already thought of that though.
