### ISSUE TITLE
Make all tracks draggable

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#61]
Not just `GenomeTrack`.

**Comment by danvk** [comment]
From the other issue:

> And let's throw a cursor: grab on there while we are at it!

**Comment by ryan-williams** [comment]
+1, was just trying to drag the reads track and was confused

**Comment by hammer** [comment]
@danvk can this be closed with #171 or are "panning" and "dragging" different actions?

**Comment by hammer** [comment]
Ah nevermind I see now that #171 was closed as a duplicate, not because it was implemented.
