### ISSUE TITLE
Minimize redrawing of pileups

### ISSUE THREAD

**Issue by danvk** [hammerlab/pileup.js#86]
This is going to require some refactoring. Currently `PileupTrack` redoes the pileup & updates all the SVG elements on every frame. Ideally it would draw a superset of the visible reads whenever new data comes in. Panning would simply involve translating the whole SVG element.

**Comment by danvk** [comment]
IGV.js does this as well and the difference is noticeable. We should be smart about re-using previously-rendered data when panning.

**Comment by danvk** [comment]
This may push us away from using React components for visualizations. Maintaining off-screen buffers is much more natural if Tracks just have to implement a `.drawImage()` method.

A simplified BufferedTrack API might look something like:

```javascript
class PileupTrack extends BufferedTrack {
  constructor(p: Pileup, source: DataSource, referenceSource: DataSource) {
    // register event listeners, save references, ...
  }

  render(ctx: DataCanvasRenderingContext2D, scale: (number)=>number, interval: ContigInterval) {
    // ... render into offscreen buffer
  }

  trackHeight(interval: ContigInterval): number {
    // determine how tall the canvas should be
  }

  handleClick(e: MouseEvent, scale: (number)=>number) {
    // possibly handle click, calling e.preventDefault() if an action was taken.
  }
}
```

There might need to be more two-way communication than this allows, though. For example, what if new data comes in and the track decides that it needs to re-render itself? Or change its height?

@ihodes @armish thoughts?

**Comment by armish** [comment]
Is this currently how you do it in your demo you showed me the other day? Maybe we can get completely rid of React and reduce the size of the library even more :)

**Comment by danvk** [comment]
My demo is using something that fits more easily into our existing code. Hopefully I can send out a PR soon :)
